export const interviewAgents = [
  {
    name: "Rohan",
    provider: "openai",
    voiceId: "echo",
    bg: "6366f1",
    image: "/assets/interviewers/male1.png",
    label: "Male",
  },
  {
    name: "Sophia",
    provider: "openai",
    voiceId: "nova",
    bg: "ec4899",
    image: "/assets/interviewers/female1.png",
    label: "Female",
  },
  {
    name: "Marcus",
    provider: "openai",
    voiceId: "onyx",
    bg: "10b981",
    image: "/assets/interviewers/male2.png",
    label: "Male",
  },
  {
    name: "Emma",
    provider: "openai",
    voiceId: "shimmer",
    bg: "8b5cf6",
    image: "/assets/interviewers/female2.png",
    label: "Female",
  },
  {
    name: "Elliot",
    provider: "vapi",
    voiceId: "Elliot",
    bg: "f59e0b",
    image: "/assets/interviewers/male3.png",
    label: "Male",
  },
  {
    name: "Rachel",
    provider: "11labs",
    voiceId: "21m00Tcm4TlvDq8ikWAM",
    bg: "E11D48",
    image: "/assets/interviewers/female3.png",
    label: "Female",
  },
  {
    name: "Drew",
    provider: "11labs",
    voiceId: "29vD33N1CtxCmqQRPOHJ",
    bg: "2563EB",
    image: "/assets/interviewers/male4.png",
    label: "Male",
  },
  {
    name: "Clyde",
    provider: "11labs",
    voiceId: "2EiwWnXFnvU5JabPnv8n",
    bg: "D97706",
    image: "/assets/interviewers/male5.png",
    label: "Male",
  },
  {
    name: "Mimi",
    provider: "11labs",
    voiceId: "zrHiDhphv9ZnVXBqCLjz",
    bg: "EC4899",
    image: "/assets/interviewers/female4.png",
    label: "Female",
  },
  {
    name: "Fin",
    provider: "11labs",
    voiceId: "D38z5RcWu1voky8WS1ja",
    bg: "059669",
    image: "/assets/interviewers/male6.png",
    label: "Male",
  },
  {
    name: "Nicole",
    provider: "11labs",
    voiceId: "piTKgcLEGmPE4e6mEKli",
    bg: "7C3AED",
    image: "/assets/interviewers/female5.png",
    label: "Female",
  },
];
